"""Add banner fields

Revision ID: 2ebcfe7e207d
Revises: 
Create Date: 2026-08-11 14:33:35.280787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ebcfe7e207d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('banner_title', sa.String(), nullable=True))
    op.add_column('products', sa.Column('banner_subtitle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'banner_subtitle')
    op.drop_column('products', 'banner_title')
    # ### end Alembic commands ###
