"""Add product description component fields

Revision ID: 5e94b4abb0f7
Revises: 2ebcfe7e207d
Create Date: 2026-08-15 10:59:53.305722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e94b4abb0f7'
down_revision: Union[str, Sequence[str], None] = '2ebcfe7e207d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description_title', sa.String(), nullable=True))
    op.add_column('products', sa.Column('description_points', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('description_list_style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description_list_style')
    op.drop_column('products', 'description_points')
    op.drop_column('products', 'description_title')
    # ### end Alembic commands ###
