events {}

http {
    server {
        listen 80;
        server_name meewaindustries.com www.meewaindustries.com localhost;

        location / {
            proxy_pass http://frontend_web:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name api.meewaindustries.com api.localhost;

        location / {
            proxy_pass http://backend_api:8000;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 80;
        server_name admin.meewaindustries.com admin.localhost;

        location / {
            proxy_pass http://admin_web:3000;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 80;
        server_name admin-api.meewaindustries.com admin-api.localhost;

        location / {
            proxy_pass http://admin_api:8001;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 80;
        server_name storage.meewaindustries.com storage.localhost;

        location / {
            proxy_pass http://minio:9000;
            proxy_set_header Host $host;
        }
    }
}
